export const mockTabData = [
  {
    id: 1,
    title: "Mock Test 1",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "completed",
    marks: {
      scored: 25,
      total: 100,
    },
    action: "completed",
  },
  {
    id: 2,
    title: "Mock Test 2",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "not_started",
    action: "start",
  },
  {
    id: 3,
    title: "Mock Test 3",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "not_started",
    action: "start",
  },
  {
    id: 4,
    title: "Mock Test 4",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "not_started",
    action: "start",
  },
  {
    id: 5,
    title: "Mock Test 5",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "not_started",
    action: "start",
  },
  {
    id: 6,
    title: "Mock Test 6",
    questions: 20,
    durationMinutes: 30,
    sections: ["Aptitude", "Technical", "Coding"],
    status: "not_started",
    action: "start",
  },
];
