export const practiceTabData = [
  {
    category: "Aptitude",
    tests: [
      {
        id: "apt-1",
        title: "Practice Test 1",
        type: "aptitude",
        questionsCount: 20,
        codingQuestions: 0,
        durationMins: 30,
        status: "completed",
      },
      {
        id: "apt-2",
        title: "Practice Test 2",
        type: "aptitude",
        questionsCount: 30,
        codingQuestions: 0,
        durationMins: 30,
        status: "start",
      },
      {
        id: "apt-3",
        title: "Practice Test 3",
        type: "aptitude",
        questionsCount: 30,
        codingQuestions: 0,
        durationMins: 30,
        status: "start",
      },
      {
        id: "apt-4",
        title: "Practice Test 4",
        type: "aptitude",
        questionsCount: 30,
        codingQuestions: 0,
        durationMins: 30,
        status: "start",
      },
    ],
  },

  {
    category: "Technical",
    tests: [
      {
        id: "tech-1",
        title: "Practice Test 1",
        type: "technical",
        codingQuestions: 2,
        questionsCount: 10,
        durationMins: 30,
        status: "completed",
      },
      {
        id: "tech-2",
        title: "Practice Test 2",
        type: "technical",
        codingQuestions: 2,
        questionsCount: 30,
        durationMins: 30,
        status: "completed",
      },
      {
        id: "tech-3",
        title: "Practice Test 3",
        type: "technical",
        codingQuestions: 2,
        questionsCount: 0,
        durationMins: 30,
        status: "completed",
      },
      {
        id: "tech-4",
        title: "Practice Test 4",
        type: "technical",
        codingQuestions: 0,
        questionsCount: 30,
        durationMins: 30,
        status: "start",
      },
    ],
  },
];
